# Uncomment this line to define a global platform for your project
 platform :ios, ‘9.0’

target 'YACSiOS' do
pod 'AFNetworking'
pod 'Masonry'
end

target 'YACSiOSTests' do

end

target 'YACSiOSUITests' do

end

